## Немного про модуль `numpy`

Скачиваем: 

```python
!pip3 install numpy
```

Подгружаем: 

```python
import numpy as np
```

In [11]:
import numpy as np

### 1. Списки в numpy

__Имеем обычный список в python:__

In [16]:
l = [1, 2, 10, -1, -2, 0, -100]

print(l)
print(type(l))

[1, 2, 10, -1, -2, 0, -100]
<class 'list'>


Хотим прибавить к каждому значению 5:

In [8]:
# так не работает :(
l + 5

TypeError: can only concatenate list (not "int") to list

In [9]:
# придется делать так
[el + 5 for el in l]

[6, 7, 15, 4, 3, 5, -95]

Хотим отобрать только положительные значения. Можем сделать так:

In [4]:
[el for el in l if el > 0]

[1, 2, 10]

__Пусть теперь мы имеем numpy-список:__

In [17]:
npl = np.array(l)

print(npl)
print(type(npl))

[   1    2   10   -1   -2    0 -100]
<class 'numpy.ndarray'>


> В numpy-списке операции векторизованные! То есть можно применять любую операцию к каждому элементу списка

Хотим прибавить к каждому значению 5:

In [18]:
# теперь работает
npl + 5

array([  6,   7,  15,   4,   3,   5, -95])

Хотим отобрать только положительные значения:

In [19]:
# теперь можно через срезы, как в pandas
npl[npl > 0]

array([ 1,  2, 10])

### 2. Статистики в numpy

В пакете `numpy` есть куча функций для подсчета различных статистических метрик:

- `np.min(x)` – найдет минимальный элемент
- `np.max(x)` – найдет максимальный элемент
- `np.sum(x)` – посчитает сумму
- `np.mean(x)` – посчитает среднеее
- `np.var(x)` – посчитает дисперсию
- `np.median(x)` – посчитает медиану
- `np.quantile(x, q=0.05)` – посчитает квантиль уровня 0.05

Про остальные функции можно почитать в официальной документации.

In [21]:
x = [1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 10]

np.quantile(x, 0.5) # медиана через квантиль

3.0

### 3. Случайности в numpy

В модуле `numpy.random` есть куча функций для случайностей, вот основные из них:

- `np.random.shuffle(x)` – перемешает элементы в массиве $x$ – inplace method!
- `np.random.rand(n)` – сгенерирует $n$ случайных чисел от 0 до 1 (равномерное распределение)
- `np.random.randint(start, end, n)` – сгенерирует $n$ целых чисел от $start$ до $end$
- `np.random.random()` – сгенерирует одно случайной число от 0 до 1 (равномерное распределение)
- `np.random.choice(x, size=n, replace=True, p=probs)` – сгенерирует $n$ чисел из массива $x$ с повторениями (`replace=True`) и вероятностями $probs$ на каждое значение

Про остальные функции можно почитать в официальной документации.

In [29]:
x = [1, 2, 3, 4]
print(x) 
np.random.shuffle(x) # перемешали массив
print(x)

[1, 2, 3, 4]
[2, 4, 1, 3]


In [31]:
# получили 4 вещественных числа от 0 до 1 
np.random.rand(4)

array([0.99940827, 0.48049502, 0.79744227, 0.90024729])

In [32]:
# получили 3 целых числа от 10 до 20
np.random.randint(10, 20, 3)

array([13, 11, 11])

In [33]:
# получили одно вещественное число от 0 до 1
np.random.random()

0.890146900803032

In [35]:
# подкинули неправильную монетку, у которой вероятность выпадения решки 0.7
np.random.choice(['Орел', 'Решка'], size=1, p=[0.3, 0.7])

array(['Решка'], dtype='<U5')

In [36]:
# равновероятно вытащили 2 числа из массива [1, 2, 3, 4, 5] с возможностью повторов
np.random.choice([1, 2, 3, 4, 5], size=2, replace=True)

array([2, 5])

In [38]:
# вытащили 2 числа из массива [1, 2, 3, 4, 5] с возможностью повторов
# делаем это НЕравновероятно, а со своими вероятностями, которые придумали
numbers = [1, 2, 3, 4, 5]
probs = [0.1, 0.2, 0.3, 0.2, 0.2]

np.random.choice(numbers, size=2, replace=True, p=probs)

array([4, 3])